# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate Solved Problem List

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn install
      
      - name: Generate markdown file
      - run: yarn generate 

      # Commits all changed files to the repository
      - name: Commit to the repo
        run: |
          git config --global user.name "ZeroOnePro"
          git config --global user.email "dbtjdals1771@ajou.ac.kr"
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit -m '해결한 문제리스트를 업데이트하였습니다.' || echo
          git push
